[world]
name = "Detective Game"
description = "A detective game where players interrogate AI-powered suspects to solve murder mysteries"
seed = "detective_game"

[env]
rpc_url = "https://api.cartridge.gg/x/detective-game-6/katana"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[namespace]
default = "detective_game"

# CRITICAL: Grant writer permissions to the actions contract
[writers]
"detective_game" = ["detective_game-actions"]

[[models]]
tag = "detective_game-Game"
description = "Game state model storing game progress and status"

[[models]]
tag = "detective_game-Player"
description = "Player statistics and current game information"

[[models]]
tag = "detective_game-Accusation"
description = "Record of player accusations and their correctness"

[[contracts]]
tag = "detective_game-actions"
description = "Main game actions contract for starting games and making accusations"